version: '3.7'

services:
  mrwde:
    image: mrwde_app:latest
    container_name: mrwde_app
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - 5173:5173
    command: |-
        sh -c '${COMMAND}'